### ISSUE TITLE
Add link to the book?

### ISSUE THREAD

**Issue by shaunlebron** [jdeisenberg/etudes-for-clojurescript#1]
just wondering if you wanted to add a link to the book somewhere in this repo.  I couldn't find it anyway

**Comment by rymndhng** [comment]
+1

**Comment by jdeisenberg** [comment]
Updated README.asciidoc to add a link to website where you can read HTML, ePub, and PDF versions. The current location (at catcode.com) may move. Let me know if this is what you had in mind; if so, I'll close the issue.

**Comment by shaunlebron** [comment]
Thanks!
